/**
 * Tier A+C+D adapter on a REAL substrate: Tetris on a Game Boy emulator
 * (PyBoy, out-of-process via pyboy/worker.py). Research claim G1's L3 gate.
 *
 * Evidence tiers exercised:
 *   A engine-state — score/lines/level decoded from RAM (map from the
 *     MIT-licensed disassembly, see pyboy/tetris.py)
 *   C save-file — sha256 of the PyBoy save-state serialization (the
 *     emulator-era save channel; the DMG Tetris cart has no battery SRAM)
 *   D screen-frame — sha256 of the RGB framebuffer
 *
 * The contract carries ZERO hand-copied constants: every hash and threshold
 * is sampled by deriveContract from the committed reference playthrough
 * (pyboy/reference-tetris.json, generated by pyboy/refbot.py), and mark
 * positions are found by event predicates (`when`), not typed in.
 *
 * Env knobs:
 *   PLAYPROOF_ROM     path to the .gb ROM (required; never committed)
 *   PLAYPROOF_PYTHON  python interpreter with pyboy installed (default python3)
 */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { deriveContract } from '../authoring'
import type { Evidence, Game } from '../runtime'
import type { MilestoneContract } from '../schema'
import { PyBoyRpc, type WorkerEvidence } from './pyboy-rpc'

const REFERENCE_PATH = fileURLToPath(new URL('../pyboy/reference-tetris.json', import.meta.url))

export interface PyBoyTetrisState {
  gen: number
  frame: number
  evidence: Evidence
  frameText: string
}

interface ReferenceFile {
  schemaVersion: 1
  gameId: string
  seed: number
  romMd5: string
  inputs: string[]
  provenance: Record<string, unknown>
}

export interface PyBoyTetris {
  game: Game<PyBoyTetrisState>
  contract: MilestoneContract
  reference: string[]
  romMd5: string
  seed: number
  dispose(): void
}

function toEvidence(w: WorkerEvidence): Evidence {
  return {
    engineState: w.engineState,
    ...(w.saveBlobHash !== undefined ? { saveBlobHash: w.saveBlobHash } : {}),
    ...(w.frameHash !== undefined ? { frameHash: w.frameHash } : {}),
  }
}

/**
 * Build the adapter. Throws if PLAYPROOF_ROM is unset or the worker cannot
 * boot — callers gate availability on pyBoyTetrisConfigured() first.
 */
export function makePyBoyTetris(): PyBoyTetris {
  const rom = process.env.PLAYPROOF_ROM
  if (!rom) throw new Error('PLAYPROOF_ROM is required for the pyboy-tetris adapter')
  const rpc = new PyBoyRpc()
  const booted = rpc.boot(rom, 'tetris')
  const gen0 = booted.gen

  const bootEv = rpc.evidence()
  const bootText = (rpc.call('frame', {}) as { text: string }).text
  let current: PyBoyTetrisState = {
    gen: gen0,
    frame: booted.frame,
    evidence: toEvidence(bootEv),
    frameText: bootText,
  }

  const game: Game<PyBoyTetrisState> = {
    id: 'pyboy-tetris',
    init: () => {
      const r = rpc.reset()
      const ev = rpc.evidence()
      const text = (rpc.call('frame', {}) as { text: string }).text
      current = { gen: r.gen, frame: r.frame, evidence: toEvidence(ev), frameText: text }
      return current
    },
    step: (s, input) => {
      // Staleness guard: gen only changes in init(), so a mismatch means a
      // caller is stepping a state captured against an older emulator boot.
      if (s.gen !== current.gen) {
        throw new Error(`stale state: gen ${s.gen} but worker is at gen ${current.gen} — step ordering violated`)
      }
      const r = rpc.step(input)
      current = { gen: current.gen, frame: r.frame, evidence: toEvidence(r.evidence), frameText: r.frameText }
      return current
    },
    frame: (s) => s.frameText,
    evidence: (s) => s.evidence,
  }

  const ref = JSON.parse(readFileSync(REFERENCE_PATH, 'utf8')) as ReferenceFile
  const contract = deriveContract(game, ref.seed, ref.inputs, tetrisMarks())

  return {
    game,
    contract,
    reference: ref.inputs,
    romMd5: ref.romMd5,
    seed: ref.seed,
    dispose: () => rpc.shutdown(),
  }
}

/** Zero-cost availability probe: env + worker deps present. */
export function pyBoyTetrisConfigured(): boolean {
  return Boolean(process.env.PLAYPROOF_ROM)
}

export function tetrisMarks() {
  return [
    {
      when: (e: Evidence) => e.engineState?.inGame === 1,
      id: 'game-started',
      tier: 'screen-frame' as const,
      glitchClass: 'legal' as const,
      sample: (e: Evidence) => ({ kind: 'frame-hash' as const, hash: e.frameHash! }),
    },
    {
      // Progression signal that any moving agent hits early: the emulator has
      // advanced well past boot (~620 frames), i.e. pieces are actually
      // falling. Soft-drop score never accumulates with discrete presses on
      // this game, so frame progression is the honest early milestone.
      when: (e: Evidence) => (e.engineState?.emuFrame ?? 0) > 710,
      id: 'first-pieces-dropped',
      tier: 'engine-state' as const,
      glitchClass: 'legal' as const,
      sample: (e: Evidence) => ({ kind: 'state-path' as const, path: 'emuFrame', op: '>=' as const, value: e.engineState?.emuFrame ?? 710 }),
    },
    {
      when: (e: Evidence) => (e.engineState?.lines ?? 0) >= 1,
      id: 'line-1',
      tier: 'engine-state' as const,
      glitchClass: 'legal' as const,
      sample: (e: Evidence) => ({ kind: 'state-path' as const, path: 'lines', op: '>=' as const, value: e.engineState?.lines ?? 1 }),
    },
    {
      when: (e: Evidence) => (e.engineState?.lines ?? 0) >= 1,
      id: 'score-after-line',
      tier: 'engine-state' as const,
      glitchClass: 'legal' as const,
      requires: ['line-1'],
      sample: (e: Evidence) => ({ kind: 'state-path' as const, path: 'score', op: '>=' as const, value: e.engineState?.score ?? 40 }),
    },
    {
      when: (e: Evidence) => (e.engineState?.lines ?? 0) >= 1,
      id: 'state-at-line-1',
      tier: 'save-file' as const,
      glitchClass: 'legal' as const,
      requires: ['line-1'],
      sample: (e: Evidence) => ({ kind: 'save-hash' as const, hash: e.saveBlobHash! }),
    },
  ]
}
